### ISSUE TITLE
Web File contents don't load

### ISSUE THREAD

**Issue by RicLund** [MscrmTools/MscrmTools.PortalCodeEditor#5] opened 2018-02-28 12:18 UTC
When I choose a stylesheet item in the contents it doesn't load - see screenshot. This is a pity as getting to and editing these as attached files is a pain! CRM is 8.1.0.359 and portal is the latest XrmPortals Community Edition.

![portalcodeeditor - styles don t load](https://user-images.githubusercontent.com/15038394/36787304-9d27951e-1c81-11e8-8406-1af69780d45e.PNG)

**Comment by MscrmTools** [comment] 2018-06-21 06:10
I don't have the same version as you but it shouldn't change anything...
I can't reproduce for now. 
Let's see with next version to be released soon

**Comment by MscrmTools** [comment] 2018-06-21 13:13
Ok I reproduced the error but the code is ok. I don't know why decoding the file base64 does not work for css whereas it works for other types. I also succeeded to decode css correctly on one of the portals

**Comment by riclund** [comment] 2019-01-09 18:43
I still see exactly the same thing - running v1.2018.6.8 of the plugin - @MscrmTools was it updated in the store with this fix or should I build the code and try it?

**Comment by MscrmTools** [comment] 2019-01-10 08:19
PR is not yet merged. I'll do it now but I don't have time to release a new version soon.

**Comment by RicLund** [comment] 2019-02-20 15:49
Hi @MscrmTools - when do you think you'll have chance to package and release the plugin update?

**Comment by MscrmTools** [comment] 2019-03-06 15:03
I will release a new version very soon :)

**Closed** 2019-10-08 05:35 UTC
